# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Parent_Native_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SwiftyJSON', '~> 4.0'
  flutter_application_path = '../Flutter_Module'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

  install_all_flutter_pods(flutter_application_path)

  post_install do |installer|
    flutter_post_install(installer)
  end

end

